### PR TITLE
Added headshot for Sam Zhuang

### PR DESCRIPTION
**Pull request by Samrfgh**
Added headshot for Sam Zhuang

### CODE REVIEW

**Review by ndattani — COMMENTED** [review]
Why have you added the file `.DS_Store` to my repository? I wonder what sequence of commands you used to push this commit?

**Comment by Samrfgh** [comment]
I used the same commands I used for all my other pushes, should I delete this one and try it again?

**Comment by ndattani** [comment]
@Samrfgh please do not close or delete this pull request. I wrote in Discord that a couple people closed their pull request and opened a new one, which is not how pull requests are intended to work. As for the commands that you used, can you please list them? I'll try to see what happened.

**Comment by Samrfgh** [comment]
Ok, here they are from terminal's history log:

857  git clone https://github.com/Samrfgh/HPQC.git
858  cd HPQC
859  cd images
860  git add SamZhuang.jpg
861  git commit -a
862  git push

**Comment by ndattani** [comment]
Did you not do anything between lines 859 and 860?

**Comment by ndattani** [comment]
During the team meeting yesterday, it was established that between lines 859 and 860, the image file was dragged and dropped into the `/images` folder and the `.DS_Store` file must have entered along with it.

Even in that case, the reason why it was part of the commit is a mystery to me, because the list of commands that you gave me does not include anything like `git add *` or `git add .DS_Store`. Do you have any idea how that file became part of the commit @vandan-revanur?

**Comment by vandan-revanur** [comment]
@ndattani 
I made an investigation into why this has happened. 

Here is the reason:

Firstly another person called Yukun Chen (@chenykfrank) has already pushed a .DS_Store file in this [commit](https://github.com/HPQC-LABS/HPQC/commit/a0ded56838318f2ef18551fd4741c5ff0c5b3249). So this file already exists on the master branch ([gh-pages](https://github.com/HPQC-LABS/HPQC) I mean)

And before @Samrfgh  ran `git commit -a`, he must have opened the HPQC folder using finder (the explorer equivalent on MacOS). So everytime one opens a folder on finder, MacOS keeps track of this by altering the contents of the .DS_Store file.

When `git commit -a` is run, it automatically stages all modified files and commits them.
As powerful as the -a flag is, this is the danger it carries with it.

So the best practice is to always individually add the required files using:

`git add file-name`

And commit them using `git commit -m`

**Comment by ndattani** [comment]
Thanks @vandan-revanur! Hopefully @Samrfgh and @chenykfrank have learned from this not to use the MacOS file explorer to add or remove files in Git. Always use the command line interface to `mv` or `rm` files. 

A second problem with this pull request is that I can't check the uploaded image because the JPG file seems to be corrupted: https://raw.githubusercontent.com/HPQC-LABS/HPQC/1950119eec9597e45a1843bbad50cff10173292e/images/SamZhuang.jpg  It is 1.5MB in size, so it looks like it could be an image, but I haven't been able to view the image. I could clone Sam's fork of the repository and check that way, but it does seem like there's some error with this image upload. For all other pull requests, I saw the image immediately, for example: https://github.com/HPQC-LABS/HPQC/pull/87/files

**Comment by ndattani** [comment]
@AbdulMuhaymin are you able to see the .jpg file? I'm not able to view it in the browser. It might be possible to see it when the file is downloaded onto a local machine.

**Comment by AbdulMuhaymin** [comment]
@ndattani I am not able to see it in a browser. It gives an 'unable to render rich display' error. When I downloaded it as a raw file and tried to open it using Windows photo viewer, it gives me an error of 'Unsupported file format or corrupted file'.

**Comment by ndattani** [comment]
@AbdulMuhaymin perhaps you can ping @Samrfgh in the Discord Git channel if Sam doesn't seem to see the messages here. I mentioned this issue here on 19 April.

**Comment by ndattani** [comment]
@Samrfgh  have you figured out the issue? I wonder why you closed the pull request? Please keep in mind that we don't want multiple pull requests to be opened for the same headshot. Please continue working on this pull request rather than opening a new one, and you can ask questions in the git channel in the HPQC Discord group if you want!

**Pull request merged**
