### PR TITLE
people.html and people.css improvements

### PR DESCRIPTION
**Pull request by maheenandcode**

### CODE REVIEW

**Review by ndattani — APPROVED** [review]

**Comment by ndattani** [comment]
@maheenandcode the pictures do not seem centered.

**Comment by maheenandcode** [comment]
> @maheenandcode the pictures do not seem centered.

image


image

Are the changes (screenshots attached) not showing up? Or  pictures are not centred in the screenshots I attached.

**Comment by ndattani** [comment]
@maheenandcode It does appear to work now! The deployment finished 47 minutes ago: https://github.com/HPQC-LABS/HPQC/actions/runs/6103922374 and my comment here was 43 minutes ago. I thought that since 4 minutes had passed, and the pictures were still not centered, the code might not have worked, but CTRL+SHIFT+R didn't seem to be understood by this iPad, so I could only try CTRL+R (and I also tried clicking the refresh button, and also closing the tab and finding the website again) and still there was no difference in the live website. 

However it does seem to work now, so maybe I just had to wait longer, or to check on a different device (if it was a caching problem).

**Comment by maheenandcode** [comment]
Makes sense!

**Pull request merged**
