### PR TITLE
Added XisenWang.png

### PR DESCRIPTION
**Pull request by xisen-w**
Uploaded and added Xisen Wang's photo

### CODE REVIEW

**Comment by ndattani** [comment]
Thank you Xisen/Jack, 
but I'm sure that you would agree that this photo is very different from every photo here: https://hpqc.org/people.html

What about the one that you have in your GitHub profile? That one seems perfect, after cropping out some of the clothes and neck so that the facial dimensions match what we have in other photos (while still making the overall dimensions the same as specified in the README file).

**Comment by xisen-w** [comment]
Ohhh I see! I'll then try to upload the photo that I use for my GitHub. (I initially thought about that, but after viewing some others' photos I uploaded the other xD.

**Comment by ndattani** [comment]
@Xisen-Wang this pull request is to remain "open" until it's merged into the main branch. Closing of pull requests is something that's done in different circumstances. 

What was it about the other pictures that made you switch to this one, in which you're not even looking at the camera? None of the other pictures have people that are not looking at the camera :laughing:

**Comment by xisen-w** [comment]
Ohh! I'm sorry. I thought that I should close this. I have cropped the 2nd photo. The reason that I switched to the previous one is that I found a lot of photos that are cropped from bigger, normal-lifestyle photos, rather than cropped from business-style photos : D

**Comment by ndattani** [comment]
Thank you @Xisen-Wang  :) That explanation for why you did it the first way, makes sense now.

**Pull request merged**
