### PR TITLE
Adding Personal Photo

### PR DESCRIPTION
**Pull request by JaafarMehrez**

### CODE REVIEW

**Comment by ndattani** [comment]
Can you please show the dimensions of the picture, such as here:

image

Also, this commit was made by Mhrzz, not by @JaafarMehrez:

image

What steps did you follow to commit and push this photo into your fork of the repository?

**Comment by JaafarMehrez** [comment]
@ndattani The steps I have taken to commit and push the file are: 
1. fork the repo 
2. clone to my personal device, mv the file to the designated folder
3. git add .
4. git commit -m 'message'
5. git push
I think the difference in names is due to using the token (maybe) as I used my email address rather than my github username. Regarding the dimensions of the image (568 × 600)pixels, I kept the same ratio. If it is not acceptable, please let me know so I can get another one.

**Comment by ndattani** [comment]
@JaafarMehrez I am curious how you ended up using an email address that is (not?) associated with your GitHub user ID? I want to make sure that future students don't make the same mistake. How would you have a "token" associated with this email address but not with your username? 

As for the ratio (568/270)*285 = 599.555555556, which is only 600 if rounded. 
Therefore 568:600 is ***not*** the same ratio as 270:285. 

How did you end up with something that has the wrong ratio? 
What software did you use to crop the photo or to change the aspect ratio?

**Comment by ndattani** [comment]
Also, I have added another sentence to the instructions here: https://github.com/HPQC-LABS/HPQC/commit/e922bde36bb2ea2799b90e0ad91d9310771e15b5, since so many people have been making the same error.

**Comment by JaafarMehrez** [comment]
@ndattani Regarding the difference in the name, I have checked and it is not because of the token itself, that's related to the git local configuations on my device, my name in the config file is 'Mhrzz' so that's why, I am gonna change it to match the one on the site. 
For the image, I have used  https://www.img2go.com/crop-image, followed the same instructions as listed in the README file by setting up the initial ration and croping from the corner!  I will refine it or change the image totally to match the required aspect ratio

**Comment by ndattani** [comment]
@JaafarMehrez Are you sure that the only issue is the name in the config file? Let's see if changing the name in the config file fixes the problem in the next commit. I'm surprised that there's no hyperlink to your GitHub profile when it says "Mhrzz" on top of the commit's webpage. 

Also, if you followed the README instructions with img2go/com/crop-image, perhaps you accidentally stretched the 270 x 285 box a little bit too much in one direction, which made your image 568 x 599.56 rather than 568 x 600. If it was 568 x 600, then it probably would have been "reduced" to 270 x 285. 

However the bigger issue is the space between the bottom of your chin and the bottom of the photo. Some people a long time ago got away with doing that, but now the rules are being much more strictly, so the space between the chin and the bottom of the photo really has to be exactly like Greg's.

**Comment by JaafarMehrez** [comment]
@ndattani, so it seems that problem was with how my name is stored locally in the config files, I have just updated that and the new commit has the same name on github page.
I believe the image should be fine now, 270x285 pixels. However, I am still not able to add a reviewer to this PR

**Comment by ndattani** [comment]
@JaafarMehrez The new image has the correct dimensions, and also has the face placed better according to the instructions. I will approve this pull request, so there is no need to add a reviewer!

**Comment by JaafarMehrez** [comment]
@ndattani, Thank you!

**Pull request merged**
