### PR TITLE
Added headshot of Esha Haque

### PR DESCRIPTION
**Pull request by EshaHaque**

### CODE REVIEW

**Review by AbdulMuhaymin — CHANGES_REQUESTED** [review]
@EshaHaque The image seems perfect to me except for the dimension which is now 368x389. The desired dimension is 270x285. That means that the aspect ratio is the same. So, you can open your image in any editor (even Microsoft Paint would do) and rescale it to 73.3695652% (or set it exactly to 270x285 px). 

Do not delete this repository, close this pull request, or start a new pull request, please. After you make the suggested changes, you can commit and then push those changes. The change will be reflected in this pull request.

**Review by AbdulMuhaymin — APPROVED** [review]

**Comment by ndattani** [comment]
@EshaHaque you do not need to delete the file when you push a new version of it.

Also, there's more space above the forehead and below the chin, compared to the standard examples (Greg, Nike, etc.).

**Comment by ndattani** [comment]
Similar to #110, which was closed because this one was earlier.

**Comment by EshaHaque** [comment]
I've updated this pull request as of yesterday; does it now fit all the requirements?

**Comment by ndattani** [comment]
@EshaHaque  I'm confused because there's only 1 commit here. Have you deleted any of the history in your branch?

**Comment by EshaHaque** [comment]
@ndattani I didn't delete anything myself so I'm not sure why the history is not visible. I think it might be because I updated the fork after new commits were made upstream, then updated the image a final time, which probably discarded any previous commits ahead that this branch had. I'm not very familiar with how pull requests work in general.

**Comment by ndattani** [comment]
Okay. In general, commits do not get deleted by updating a fork or pushing commits with new images. Do you remember why you had to use the "force push" command, and whether or not it gave you any warnings when you first ran that command?

**Comment by EshaHaque** [comment]
I don't remember whether I clicked "discard commit" or "update branch" but It looked like this:
github update branch warning

**Comment by ndattani** [comment]
Maybe clicking "Discard 1 commit" caused you to lose your commit. I always recommend people (especially beginners) to avoid using any buttons in the GitHub GUI. I only recommend to push commits, or discard commits, or update branches via the command line interface in a terminal. I would not even recommend to click "update branch" either. You have much more control if you run the appropriate commands in a terminal instead. Who knows what command is being run under the hood, by GitHub's developers, when you click a button like "update branch". 

The only buttons that I think are appropriate to press in GitHub are "Comment" and "Create Pull Request", and maybe "Re-open pull request" if you accidentally closed a pull request, but I prefer that the students don't close pull requests either, since in the recent past every time someone closed a pull request it was erroneous to do so (they closed a pull request and opened a new second pull request,  when really the best thing to do would be to update the original pull request).

**Pull request merged**
