### PR TITLE
Adding Laith Shareiyat's head shot

### PR DESCRIPTION
**Pull request by LaithShareiyat**

### CODE REVIEW

**Review by AbdulMuhaymin — CHANGES_REQUESTED** [review]
Since there's very little space between the top of the hair and the top of the photo, ideally, the bottom and sides would be somewhat symmetric in that sense. Please see the photo of Nike or Greg as the standard. Also, the requested dimension is 270x285. The dimension of the current photo is 835x881.

**Review by AbdulMuhaymin — CHANGES_REQUESTED** [review]
@SupremeDictatorI your picture is perfect. However, you used a drag-and-drop in you mac to copy/move the file and that's why a .DS_Store file is also been copied. Please remove such files. Previously, it has been strictly prohibited and the discussion can be found in https://github.com/HPQC-LABS/HPQC/pull/81

**Review by AbdulMuhaymin — APPROVED** [review]

**Review by AbdulMuhaymin — APPROVED** [review]

**Comment by ndattani** [comment]
@AbdulMuhaymin  I agree that the picture perfectly satisfies the requirements, but the .DS_Store file needs to be removed. Under "Files changed", it currently says 2, instead of 1.

Conversation surrounding *one* of the many reasons for the prohibition against using GitHub's drag-and-drop feature, indeed took place in #81, but the prohibition was also explained in the GitHub instructions.

**Comment by LaithShareiyat** [comment]
> @AbdulMuhaymin I agree that the picture perfectly satisfies the requirements, but the .DS_Store file needs to be removed. Under "Files changed", it currently says 2, instead of 1.
> 
> Conversation surrounding _one_ of the many reasons for the prohibition against using GitHub's drag-and-drop feature, indeed took place in #81, but the prohibition was also explained in the GitHub instructions.

I have reverted and re uploaded my correct image.

**Pull request merged**
