### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by frankinnutshell111**
Yizhen Chen headsht

### CODE REVIEW

**Comment by ndattani** [comment]
@frankinnutshell111 why have you added two files?

**Comment by frankinnutshell111** [comment]
One of jpg form and one of png form. I think that is required?

**Comment by ndattani** [comment]
We only need the `png` in this case. Please run the following commands from a terminal, after entering the directory called `HPQC`:

```
cd images
git rm Yizhen\ Chen.jpg
git commit -am "remove Yizhen\ Chen.jpg"
git push
```
Then enter your username and password (the Git channel on Discord has some information about what to do when asked for the username and password).

**Comment by ndattani** [comment]
Thanks @frankinnutshell111 
I see the files here: https://github.com/frankinnutshell111/HPQC/commit/edf42354ebf1072d5b015e717439908a228f19fc 
At this point you just need to run the commands that I sent you earlier in this conversation, after entering the HPQC folder.

**Review by ndattani — APPROVED** [review]

**Pull request merged**
