### PR TITLE
Adding headshot of Maheen

### PR DESCRIPTION
**Pull request by maheenandcode**

### CODE REVIEW

**Review by AbdulMuhaymin — CHANGES_REQUESTED** [review]
@maheenandcode Kindly add more facial areas and remove the surroundings. It is also suggested before to make the image symmetric on every side. So the distance between the top of the head and the top of the image should equal the distance between the bottom of the chin and the bottom of the image. The same applies to left-right. 

Do not delete this repository, close this pull request or start a new pull request, please. After you made the suggested changes, you can commit and then push those changes. The change will be reflected in this pull request.

**Review by AbdulMuhaymin — APPROVED** [review]

**Comment by ndattani** [comment]
@AbdulMuhaymin  is the most recent version of this photo centred? 
If the horizontal distance between the centre of the nose and the right side of the image is smaller than the distance from the same place to the left side of the image, then some of the building in the background could be removed too.

**Comment by ndattani** [comment]
Alternatively, @maheenandcode if you want to again do what you did last time to remove the background, you're welcome to do that on the most recent version of this photo. You can pick whichever option you prefer, out of the one described in this comment and the one described in the previous comment to Abdul.

**Comment by AbdulMuhaymin** [comment]
@ndattani It appeared centered to me. However, upon taking a closer look, I found that the center of the nose-left edge of the image is 8px longer than the center of the nose-right edge of the image.

**Comment by ndattani** [comment]
@maheenandcode did you see the above comments?

**Comment by maheenandcode** [comment]
> @maheenandcode did you see the above comments?

Yes I did! I discussed it with Abdul Muhaymin and wanted to stick with the picture that was merged.

**Comment by ndattani** [comment]
@maheenandcode where did the discussion with Abdul take place?

**Comment by maheenandcode** [comment]
> @maheenandcode where did the discussion with Abdul take place?

Discord

**Pull request merged**
