### PR TITLE
Adding DulainThannippuliGamage.png

### PR DESCRIPTION
**Pull request by DulainTG**

### CODE REVIEW

**Review by ndattani — CHANGES_REQUESTED** [review]
Thank you for this pull request! 
In order to conform to the image specifications, could you please some some of the space between the bottom of the chin and the bottom of the image, while maintaining the specified aspect ratio for the overall image? The README file in the #getting-started instructions on Discord provides a URL that allows you to crop the photo while maintaining a specified aspect ratio. 

I think Greg's photo here: https://hpqc.org/people.html is the best example. Justin, Henri, Yukun, Peilin, etc. also have perfect photos in this sense. It's true that some of the photos don't conform to this standard, but those are older photos and the staff are now cracking down more on the format. 

You just need to commit the updated photo to the same branch of your fork, and this pull request will get updated automatically.

**Comment by ndattani** [comment]
@DulainTG  you don't need to delete any branch, or close the pull request. You just need to push a new commit, and everything will happen correctly automatically, This is what I was trying to explain in my previous comment :) In the past people have closed pull requests, and made new pull requests, but I prefer everything to stay in this single pull request.

**Comment by ndattani** [comment]
I see that you did exactly that, you opened a new pull request. My original sentence:

> "You just need to commit the updated photo to the same branch of your fork, and this pull request will get updated automatically."

was meant to convey that a new branch and new pull request, are not desired.

**Comment by DulainTG** [comment]
How do I reopen a close pull request

**Comment by ndattani** [comment]
You might have to connect your GitHub profile to your computer so that when you use the terminal, your commits are actually associated with your GitHub user profile. For example, your first commit, which was done via GitHub's GUI on the website (rather than a terminal) is associated with your GitHub profile, but your second and third commits (which were done via your terminal) are not associated with your GitHub profile.

image

I'm approving this pull request now, but I suggest that you fix the above issue for future commits on GitHub.

**Pull request merged**
