### PR TITLE
added image for Harvey Wilson

### PR DESCRIPTION
**Pull request by HarveyWils**

### CODE REVIEW

**Comment by AbdulMuhaymin** [comment]
@HarveyWils could you please review the instruction given here: https://github.com/HPQC-LABS/HPQC/tree/gh-pages/images#readme ? I think this photo could be improved by cropping much of the neck and body area and including only the full face and hair. Please see the photos of Nike, Greg, and Henri on https://hpqc.org/people.html as the standard. Do not close this pull request. _You just need to commit the updated photo to the same branch of your fork, and this pull request will get updated automatically._

**Review by AbdulMuhaymin — CHANGES_REQUESTED** [review]
@HarveyWils could you please review the instruction given here: https://github.com/HPQC-LABS/HPQC/tree/gh-pages/images#readme ? I think this photo could be improved by cropping much of the neck and body area and including only the full face and hair. Please see the photos of Nike, Greg, and Henri on https://hpqc.org/people.html as the standard. Please, do not close this pull request. _You just need to commit the updated photo to the same branch of your fork, and this pull request will get updated automatically._

**Comment by HarveyWils** [comment]
Have updated now, Is that better?

**Comment by ndattani** [comment]
Thanks Harvey, and thanks Abdul for noticing the issue with the facial dimensions.

**Pull request merged**
