### PR TITLE
Adding headshot of Tejas Krishnan

### PR DESCRIPTION
**Pull request by krishte**

### CODE REVIEW

**Comment by ndattani** [comment]
@AbdulMuhaymin I wasn't able to add you as a reviewer for some reason, so I'm pinging you here instead!

**Comment by AbdulMuhaymin** [comment]
@ndattani I am not sure why this happened. I will review my GitHub setting. About the image, the dimension is correct (270x285) and the headshot seems symmetric too. You might want to review if the facial area seems to be too small. [Here ](https://raw.githubusercontent.com/HPQC-LABS/HPQC/831b09688ba976b7f5d67845d5488aa6d239db4b/images/TejasKrishnan.png)is the raw image.

**Comment by ndattani** [comment]
@AbdulMuhaymin you can provide the same advice about facial dimensions that I gave you.

**Review by AbdulMuhaymin — CHANGES_REQUESTED** [review]
@krishte the photograph is symmetric and the dimension is correct. Could you please increase the facial area? You don't need to put much of the neck or empty space. Please see the photos of Nike and Greg about the facial area from [https://hpqc.org/people.html](https://hpqc.org/people.html) and keep the dimension the same as this one.

**Comment by krishte** [comment]
@AbdulMuhaymin I've just pushed an updated photo with more facial area.

**Review by AbdulMuhaymin — APPROVED** [review]

**Pull request merged**
