### PR TITLE
Mia Hippisley photo 

### PR DESCRIPTION
**Pull request by miahippisley**
MiaHippisley (1)

### CODE REVIEW

**Comment by ndattani** [comment]
Thank you for this pull request (I can't tag you in this comment, probably because you're not yet a member of the HPQC GitHub group). Indeed you added this photo on April 10th but didn't make a pull request it seems. 

@AbdulMuhaymin, @maheenandcode, @EmilyyyLiang, @EshaHaque, @diyadrabu, or @sahnas02 (again it seems I can't tag Sahana for the same reason as described above) can review your pull request before it gets approved to get merged into the main branch. Whoever sees this first can review the pull request.

**Review by EshaHaque — CHANGES_REQUESTED** [review]
Thank you for uploading your picture! We will add it to the site as soon as this PR gets approved and merged. However, I think the reason it was not yet approved is because the preferred cropping for the images is more centered on the face, for example: https://github.com/HPQC-LABS/HPQC/blob/gh-pages/images/NikeDattani.png. Other than that, it looks like the dimensions and formatting are good :)

**Comment by ndattani** [comment]
Other good examples are the photos of Greg, Justin, Henri, etc. (not too much space below the chin and not too much space above the head, here's instructions for how to crop the photo while still having the correct height and width: https://github.com/HPQC-LABS/HPQC/blob/gh-pages/images/README.txt).

**Comment by miahippisley** [comment]
MiaHippisley (1) (1)

**Comment by miahippisley** [comment]
Is that better?

**Comment by ndattani** [comment]
It's better. Though we might get complaints about the space between the chin and the bottom of the photo (it's a bit like a passport photo in terms of the requirements). Also, the image in your comment, is not the one in your fork: https://github.com/HPQC-LABS/HPQC/pull/117/files

**Pull request merged**
