### PR TITLE
Adding headshot of Diya Drabu

### PR DESCRIPTION
**Pull request by diyadrabu**

### CODE REVIEW

**Comment by ndattani** [comment]
@AbdulMuhaymin I would appreciate if you can help review this pull request. The dimension specifications for the picture needs to be corrected, as I also explained here: https://github.com/HPQC-LABS/HPQC/pull/106#issuecomment-1636681210

Also, I have closed #105  since it was a duplicate of this PR (#104). In the HPQC Discord server there has been sone discussion about reopening the original pull request in situations like this.

**Comment by ndattani** [comment]
@AbdulMuhaymin I would appreciate if you can help review this pull request. The dimension specifications for the picture needs to be corrected, as I also explained here: https://github.com/HPQC-LABS/HPQC/pull/106#issuecomment-1636681210

Also, I have closed #105  since it was a duplicate of this PR (#104). In the HPQC Discord server there has been sone discussion about reopening the original pull request in situations like this.

**Comment by ndattani** [comment]
@AbdulMuhaymin I would appreciate if you can help review this pull request. The dimension specifications for the picture needs to be corrected, as I also explained here: https://github.com/HPQC-LABS/HPQC/pull/106#issuecomment-1636681210

Also, I have closed #105  since it was a duplicate of this PR (#104). In the HPQC Discord server there has been sone discussion about reopening the original pull request in situations like this.

**Comment by ndattani** [comment]
The only way that I see for reopening a pull request that someone else has closed, is to write a ***second*** comment, so that is what I'm doing now.

**Comment by AbdulMuhaymin** [comment]
@ndattani It seems that both of the pull requests (#104 and #105) have been closed. Now, #104 should be reopened. @diyadrabu  you can follow [this HPQC Discord conversation](https://discord.com/channels/929956709542293504/930201331388522536/1127077982327013506) on reopening a pull request. 

The dimension of your picture is correct which is 270x285. However, the image should contain as much facial area as you can afford. Please see the photos of Nike Dattani or Greg Juhasz from [here ](https://hpqc.org/people.html) as the standard. You can make this above mentioned change to your file, commit the changes, and then you should be able to reopen this pull request (now the reopen button should be greyed out for you).

**Comment by diyadrabu** [comment]
The repository this pull request was created from was deleted by me because I was using my relative's laptop then, and the global values of username and email where hers and not mine. So I decided to delete this repository, change the global variables of name and email to contain my information, created a new repository and raised a pull request, which is #105. I'm not sure if I can get back the original repository. @AbdulMuhaymin could you please suggest how to proceed?

**Comment by ndattani** [comment]
@diyadrabu Yizhen had also deleted his repository, but told me that he was contacting GtiHub support to get it back, and then very soon afterwards he was able to reopen his pull request.

**Comment by ndattani** [comment]
@diyadrabu I'm happy to see that you were able to reopen this pull request! The new picture does seem to have better resolution/quality compared to the first picture, but there's some space between the top of the head and the top of the image, plus some space between the bottom of the chin and the bottom of the image. Please see the photos of me (Nike Dattani) and of Greg, to see examples of the required dimensions. In the README file, there's a link to a site in which you can maintain the aspect ratio of 270x285 while cropping the photo to meet the specifications.

**Pull request merged**
